export enum PixwayAPIRoutes {
  COMPANY_BY_ID = 'companies/hosts/{companyId}',
  SIGN_IN = 'auth/signin',
  REQUEST_PASSWORD_CHANGE = 'auth/request-password-reset',
  RESET_PASSWORD = 'auth/reset-password',
  REFRESH_TOKEN = 'auth/refresh-token',
  GET_PROFILE = 'users/profile',
  TOKENS = '/connect/tokens',
  TOKEN_DETAILS = '/connect/tokens/{contractAddress}/{chainId}/{tokenId}',
  CONFIG = '/connect/configurations',
  NFTS_BY_WALLET = 'metadata/nfts/{address}/{chainId}',
  METADATA_BY_RFID = 'metadata/rfid/{rfid}',
  METADATA_BY_CHAINADDRESS_AND_TOKENID = 'metadata/address/{contractAddress}/{chainId}/{tokenId}',
  TOKEN_COLLECTIONS = '{companyId}/token-collections',
  CATEGORIES = 'categories',
  USERS = 'users/',
  VERIFY_SIGN_UP = '/auth/verify-sign-up',
  REQUEST_CONFIRMATION_MAIL = '/auth/request-confirmation-email',
}
