export enum PixwayAppRoutes {
  HOME = '/',
  ABOUT = '/about',
  TEAMS = '/teams',
  MARKETPLACE = '/marketplace',
  FAQ = '/faq',
  SIGN_UP = '/auth/signUp',
  SIGN_IN = '/auth/signIn',
  CONNECT_EXTERNAL_WALLET = '/auth/completeSignup/connectExternalWallet',
  REQUEST_PASSWORD_CHANGE = '/auth/changePassword/request',
  MY_PROFILE = '/profile',
  RESET_PASSWORD = '/auth/changePassword/newPassword',
  CHECKOUT_CONFIRMATION = '/checkout/confirmation',
  CHECKOUT_PAYMENT = '/checkout/payment',
  CHECKOUT_PROCESSING = '/checkout/processing',
  CHECKOUT_COMPLETED = '/checkout/completed',
  PROFILE = '/profile',
  MY_TOKENS = '/tokens',
  WALLET = '/wallet',
  SETTINGS = '/settings',
  HELP = '/help',
}
