export enum PixwayAppRoutes {
  HOME = '/',
  ABOUT = '/about',
  TEAMS = '/teams',
  MARKETPLACE = '/marketplace',
  FAQ = '/faq',
  SIGN_UP = '/auth/signUp',
  SIGN_IN = '/auth/signIn',
  CONNECT_EXTERNAL_WALLET = '/auth/completeSignup/connectExternalWallet',
  REQUEST_PASSWORD_CHANGE = '/auth/changePassword/request',
  MY_PROFILE = '/profile',
  MY_TOKENS = '/profile/tokens',
  WALLET = '/profile/wallet',
  SETTINGS = '/profile/settings',
  HELP = '/help-center',
  RESET_PASSWORD = '/auth/changePassword/newPassword',
  PROFILE = '/profile',
  MY_TOKENS = '/tokens',
  WALLET = '/wallet',
  SETTINGS = '/settings',
  HELP = '/help',
}
