export enum TokenizationAction {
  MUTATE_CONTRACT_STEP,
  MUTATE_CATEGORY_STEP,
  MUTATE_GENERAL_INFORMATION_STEP,
  MUTATE_DYNAMIC_FORM_STEP,
  MUTATE_RFID_STATE,
  MUTATE_IMAGES_URLS,
  MUTATE_DRAFT_ID,
  LOAD_DRAFT,
  RESET,
}
