export enum TokenizationFieldTypes {
  SELECT = 'SELECT',
  TEXTFIELD = 'TEXTFIELD',
  TEXTAREA = 'TEXTAREA',
  DATE = 'DATE',
  SINGLE_IMAGE = 'SINGLE_IMAGE',
  DIMENSIONS_2D = 'DIMENSIONS_2D',
  DIMENSIONS_3D = 'DIMENSIONS_3D',
  RADIOGROUP = 'RADIOGROUP',
  NUMERIC_TEXTFIELD = 'NUMERIC_TEXTFIELD',
  YEAR = 'YEAR',
}
